-- =============================================================================
-- M1 - Ciudadanos, Organizaciones y Expedientes Digitales
-- Paso 2 de 2: tablas, restricciones e indices.
--
-- Ejecutar CONECTADO A ciudadanos_m1:
--   psql -U ciudadanos_app -d ciudadanos_m1 -f 01_schema.sql
--
-- Fuente: diagrama_db_desarrollo_de_apps_2.json (draw.io). Los desvios respecto
-- del diagrama estan comentados linea por linea y listados en el README.
--
-- Este esquema es el contrato que valida Hibernate al arrancar
-- (spring.jpa.hibernate.ddl-auto=validate): si cambia una entidad, cambia aca.
-- Los estados van como VARCHAR + CHECK porque las entidades usan
-- @Enumerated(EnumType.STRING).
-- ======

BEGIN;

-- ---------------------------------------------------------------- PERSONAS ---

-- Raiz de la jerarquia: toda persona (fisica o juridica) tiene una fila aca.
CREATE TABLE persona (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo       VARCHAR(10) NOT NULL,
    -- DESVIO: el diagrama dice INT, pero un CUIT/CUIL tiene 11 digitos y no
    -- entra en un entero de 32 bits.
    cuit       BIGINT      NOT NULL,
    -- AGREGADO: POST /auth/register devuelve creadoEn.
    creado_en  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_persona_cuit UNIQUE (cuit),
    CONSTRAINT ck_persona_tipo CHECK (tipo IN ('CIUDADANO', 'JURIDICA'))
);

-- Domicilios/propiedades. Va antes de ciudadano porque este la referencia.
CREATE TABLE propiedades (
    propiedad_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo         VARCHAR(100) NOT NULL,
    calle        VARCHAR(255) NOT NULL,
    numero       VARCHAR(50)  NOT NULL,
    -- DESVIO: el diagrama la marca NOT NULL, pero POST /personas/{id}/domicilios
    -- no recibe altura.
    altura       VARCHAR(50),
    id_barrio    UUID,
    longitud     VARCHAR(50),
    latitud      VARCHAR(50)
);

-- Persona fisica. Comparte PK con persona.
-- DESVIO: el diagrama dibuja documento_id -> documento.documento_id, pero es
-- VARCHAR(255) contra un INT: no puede ser esa FK. Es el DNI, que es lo que
-- consultan RF-06 y GET /ciudadanos/dni/{dni}.
CREATE TABLE ciudadano (
    persona_id       BIGINT       PRIMARY KEY,
    documento_id     VARCHAR(255) NOT NULL,
    nombre           VARCHAR(255) NOT NULL,
    apellido         VARCHAR(255) NOT NULL,
    fecha_nacimiento DATE         NOT NULL,
    estado           VARCHAR(50)  NOT NULL DEFAULT 'ACTIVO',
    domicilio_id     BIGINT,
    CONSTRAINT fk_ciudadano_persona   FOREIGN KEY (persona_id)   REFERENCES persona (id) ON DELETE CASCADE,
    CONSTRAINT fk_ciudadano_domicilio FOREIGN KEY (domicilio_id) REFERENCES propiedades (propiedad_id),
    CONSTRAINT uk_ciudadano_dni       UNIQUE (documento_id),
    CONSTRAINT ck_ciudadano_estado    CHECK (estado IN ('ACTIVO', 'INACTIVO', 'FALLECIDO', 'BLOQUEADO'))
);

-- Persona juridica. Comparte PK con persona.
-- "nombre" es el del diagrama y se usa como nombre de fantasia, igual que en
-- organizacion. AGREGADOS: razon_social y estado, que devuelve /auth/register.
CREATE TABLE persona_juridica (
    persona_id        BIGINT       PRIMARY KEY,
    razon_social      VARCHAR(255) NOT NULL,
    nombre            VARCHAR(50)  NOT NULL,
    -- DESVIO: el diagrama la marca NOT NULL, pero el alta no la pide.
    fecha_de_creacion DATE,
    estado            VARCHAR(50)  NOT NULL DEFAULT 'ACTIVO',
    CONSTRAINT fk_juridica_persona FOREIGN KEY (persona_id) REFERENCES persona (id) ON DELETE CASCADE,
    CONSTRAINT ck_juridica_estado  CHECK (estado IN ('ACTIVO', 'INACTIVO', 'FALLECIDO', 'BLOQUEADO'))
);

-- contrasenasPersonas del diagrama.
-- DESVIO: password es VARCHAR(100), no VARCHAR(50): un hash BCrypt ocupa 60
-- caracteres y no entraria. Se guarda el hash, nunca la clave en claro.
CREATE TABLE credencial_persona (
    persona_id BIGINT       PRIMARY KEY,
    password   VARCHAR(100) NOT NULL,
    CONSTRAINT fk_credencial_persona FOREIGN KEY (persona_id) REFERENCES persona (id) ON DELETE CASCADE
);

-- Grupo familiar (RF-16..18).
CREATE TABLE relacion (
    relacion_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ciudadano_id_1       BIGINT       NOT NULL,
    ciudadano_id_2       BIGINT       NOT NULL,
    relacion_ciudadano_1 VARCHAR(100) NOT NULL,
    relacion_ciudadano_2 VARCHAR(100) NOT NULL,
    es_responsable       BOOLEAN      NOT NULL DEFAULT FALSE,
    -- AGREGADO: POST /relaciones devuelve creadoEn.
    creado_en            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_relacion_ciudadano_1 FOREIGN KEY (ciudadano_id_1) REFERENCES ciudadano (persona_id) ON DELETE CASCADE,
    CONSTRAINT fk_relacion_ciudadano_2 FOREIGN KEY (ciudadano_id_2) REFERENCES ciudadano (persona_id) ON DELETE CASCADE,
    -- Nadie se relaciona consigo mismo, y el par no se duplica.
    CONSTRAINT ck_relacion_distintos   CHECK (ciudadano_id_1 <> ciudadano_id_2),
    CONSTRAINT uk_relacion_par         UNIQUE (ciudadano_id_1, ciudadano_id_2)
);

-- ---------------------------------------------------------------- CONTACTO ---

CREATE TABLE contacto_ciudadano (
    contacto_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo          VARCHAR(50)  NOT NULL,
    valor         VARCHAR(255) NOT NULL,
    verificado    BOOLEAN      NOT NULL DEFAULT FALSE,
    -- AGREGADOS: los devuelven PATCH /contactos/{id}/verificar y el POST.
    verificado_en TIMESTAMPTZ,
    creado_en     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_contacto_tipo CHECK (tipo IN ('EMAIL', 'TELEFONO'))
);

-- Tabla puente. La columna se llama ciudadano_id, pero en el diagrama la flecha
-- apunta a persona: se respeta la flecha, asi una juridica tambien puede tener
-- contactos.
CREATE TABLE contacto_persona (
    ciudadano_id BIGINT NOT NULL,
    contacto_id  BIGINT NOT NULL,
    PRIMARY KEY (ciudadano_id, contacto_id),
    CONSTRAINT fk_contacto_persona_persona  FOREIGN KEY (ciudadano_id) REFERENCES persona (id) ON DELETE CASCADE,
    CONSTRAINT fk_contacto_persona_contacto FOREIGN KEY (contacto_id)  REFERENCES contacto_ciudadano (contacto_id) ON DELETE CASCADE
);

-- --------------------------------------------------------------- DOMICILIOS ---

-- Vinculo persona-domicilio con vigencia (RF-09..12). La baja cierra
-- vigente_hasta; la fila no se borra, para conservar el historial.
CREATE TABLE personas_propiedades (
    id_persona    BIGINT  NOT NULL,
    id_propiedad  BIGINT  NOT NULL,
    vigente_desde DATE    NOT NULL DEFAULT CURRENT_DATE,
    vigente_hasta DATE,
    -- AGREGADO: RF-10/RF-12 piden marcar el domicilio principal.
    es_principal  BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (id_persona, id_propiedad),
    CONSTRAINT fk_pp_persona   FOREIGN KEY (id_persona)   REFERENCES persona (id) ON DELETE CASCADE,
    CONSTRAINT fk_pp_propiedad FOREIGN KEY (id_propiedad) REFERENCES propiedades (propiedad_id) ON DELETE CASCADE,
    CONSTRAINT ck_pp_vigencia  CHECK (vigente_hasta IS NULL OR vigente_hasta >= vigente_desde)
);

-- RF-10: a lo sumo un domicilio principal vigente por persona.
CREATE UNIQUE INDEX uk_pp_principal_vigente
    ON personas_propiedades (id_persona)
    WHERE es_principal AND vigente_hasta IS NULL;

-- ----------------------------------------------------------- ORGANIZACIONES ---

CREATE TABLE organizacion (
    organizacion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tax_id          VARCHAR(255) NOT NULL,
    razon_social    VARCHAR(255) NOT NULL,
    -- Nombre de fantasia.
    nombre          VARCHAR(255),
    tipo            VARCHAR(100) NOT NULL,
    estado          VARCHAR(50)  NOT NULL DEFAULT 'ACTIVA',
    -- DESVIO: BIGINT por los 11 digitos del CUIT (el diagrama dice INT).
    cuit            BIGINT       NOT NULL,
    -- AGREGADO: POST /organizaciones devuelve creadoEn.
    creado_en       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uk_organizacion_tax_id UNIQUE (tax_id),
    CONSTRAINT uk_organizacion_cuit   UNIQUE (cuit),
    CONSTRAINT ck_organizacion_estado CHECK (estado IN ('ACTIVA', 'INACTIVA', 'BLOQUEADA'))
);

-- Duenos/titulares (RF-19).


CREATE TABLE persona_organizacion (
    id_persona             BIGINT      NOT NULL,
    id_organizacion        BIGINT      NOT NULL,
    -- AGREGADOS: los devuelven los endpoints de duenos.
    porcentaje_titularidad NUMERIC(5, 2),
    asociado_en            TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (id_persona, id_organizacion),
    CONSTRAINT fk_po_persona      FOREIGN KEY (id_persona)      REFERENCES persona (id) ON DELETE CASCADE,
    CONSTRAINT fk_po_organizacion FOREIGN KEY (id_organizacion) REFERENCES organizacion (organizacion_id) ON DELETE CASCADE,
    CONSTRAINT ck_po_porcentaje   CHECK (porcentaje_titularidad IS NULL
                                         OR (porcentaje_titularidad > 0 AND porcentaje_titularidad <= 100))
);

-- Poder para operar en nombre de una organizacion (RF-20..22).
CREATE TABLE representacion (
    representacion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    persona_id        BIGINT       NOT NULL,
    organizacion_id   BIGINT       NOT NULL,
    alcance           VARCHAR(255) NOT NULL,
    desde             DATE         NOT NULL,
    hasta             DATE,
    estado            VARCHAR(50)  NOT NULL DEFAULT 'VIGENTE',
    CONSTRAINT fk_representacion_persona      FOREIGN KEY (persona_id)      REFERENCES persona (id) ON DELETE CASCADE,
    CONSTRAINT fk_representacion_organizacion FOREIGN KEY (organizacion_id) REFERENCES organizacion (organizacion_id) ON DELETE CASCADE,
    CONSTRAINT ck_representacion_estado       CHECK (estado IN ('VIGENTE', 'VENCIDA', 'REVOCADA')),
    CONSTRAINT ck_representacion_fechas       CHECK (hasta IS NULL OR hasta >= desde)
);

-- RF-22: una sola representacion VIGENTE por par persona-organizacion.
CREATE UNIQUE INDEX uk_representacion_vigente
    ON representacion (persona_id, organizacion_id)
    WHERE estado = 'VIGENTE';

-- Ciudadanos que integran una persona juridica (RF-03). Tabla puente pura.
CREATE TABLE integrantes_personas_juridicas (
    id_ciudadano        BIGINT NOT NULL,
    id_persona_juridica BIGINT NOT NULL,
    PRIMARY KEY (id_ciudadano, id_persona_juridica),
    CONSTRAINT fk_ipj_ciudadano FOREIGN KEY (id_ciudadano)        REFERENCES ciudadano (persona_id) ON DELETE CASCADE,
    CONSTRAINT fk_ipj_juridica  FOREIGN KEY (id_persona_juridica) REFERENCES persona_juridica (persona_id) ON DELETE CASCADE
);

-- ----------------------------------------------------------- DOCUMENTACION ---

-- Documentacion cargada por/para una persona (RF-23..26).
-- El diagrama no dibuja la flecha persona_id -> persona, pero la columna dice
-- "personaid INT NOT NULL": se implementa la FK.
CREATE TABLE documento (
    documento_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    persona_id           BIGINT       NOT NULL,
    tipo_documento       VARCHAR(100) NOT NULL,
    version              INTEGER      NOT NULL DEFAULT 1,
    vigencia_hasta       DATE,
    cargado_por          VARCHAR(255) NOT NULL,
    validado_por         VARCHAR(255),
    -- AGREGADOS: GET /documentos/{id}, POST /documentos y PATCH .../validar.
    url_archivo          VARCHAR(500),
    resultado_validacion VARCHAR(50)  NOT NULL DEFAULT 'PENDIENTE',
    fecha_validacion     TIMESTAMPTZ,
    fecha_creacion       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_documento_persona   FOREIGN KEY (persona_id) REFERENCES persona (id) ON DELETE CASCADE,
    CONSTRAINT ck_documento_version   CHECK (version >= 1),
    CONSTRAINT ck_documento_resultado CHECK (resultado_validacion IN ('PENDIENTE', 'VALIDADO', 'RECHAZADO'))
);

-- Pedido de documentacion faltante (RF-27..29).
CREATE TABLE solicitud_documentacion (
    solicitud_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titular_id     BIGINT       NOT NULL,
    tipo_documento VARCHAR(100) NOT NULL,
    plazo          DATE         NOT NULL,
    estado         VARCHAR(50)  NOT NULL DEFAULT 'PENDIENTE',
    origen         VARCHAR(100) NOT NULL DEFAULT 'INTERNA',
    documento_id   BIGINT,
    -- AGREGADO: POST /solicitudes-documentacion devuelve creadoEn.
    creado_en      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_solicitud_titular   FOREIGN KEY (titular_id)   REFERENCES persona (id) ON DELETE CASCADE,
    CONSTRAINT fk_solicitud_documento FOREIGN KEY (documento_id) REFERENCES documento (documento_id),
    CONSTRAINT ck_solicitud_estado    CHECK (estado IN ('PENDIENTE', 'CUMPLIDA', 'VENCIDA')),
    CONSTRAINT ck_solicitud_origen    CHECK (origen IN ('INTERNA', 'EVENTO')),
    -- RF-28: no se puede dar por cumplida sin el documento que la satisface.
    CONSTRAINT ck_solicitud_cumplida  CHECK (estado <> 'CUMPLIDA' OR documento_id IS NOT NULL)
);

-- ------------------------------------------------------------- EXPEDIENTES ---

CREATE TABLE expediente (
    expediente_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero          VARCHAR(100) NOT NULL,
    persona_id      BIGINT       NOT NULL,
    area_iniciadora VARCHAR(255) NOT NULL,
    estado          VARCHAR(50)  NOT NULL DEFAULT 'INICIADO',
    caratula        VARCHAR(255) NOT NULL,
    fecha_inicio    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_expediente_persona FOREIGN KEY (persona_id) REFERENCES persona (id),
    CONSTRAINT uk_expediente_numero  UNIQUE (numero),
    CONSTRAINT ck_expediente_estado  CHECK (estado IN ('INICIADO', 'EN_TRAMITE', 'RESUELTO', 'ARCHIVADO'))
);

-- Movimientos del expediente (RF-33..35). actuacion_id es el numero de orden
-- dentro del expediente, no un id global.
CREATE TABLE actuacion (
    expediente_id BIGINT       NOT NULL,
    actuacion_id  BIGINT       NOT NULL,
    tipo          VARCHAR(100) NOT NULL,
    modulo_origen VARCHAR(100) NOT NULL,
    descripcion   TEXT         NOT NULL,
    fecha         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    -- JSON serializado con las referencias externas a archivos (RF-34).
    adjuntos      TEXT,
    PRIMARY KEY (expediente_id, actuacion_id),
    CONSTRAINT fk_actuacion_expediente FOREIGN KEY (expediente_id) REFERENCES expediente (expediente_id) ON DELETE CASCADE
);

-- --------------------------------------------------------------- EMPLEADOS ---

-- AGREGADOS: mail (POST /auth/empleados/login recibe mail) y activo (da 403 si
-- el empleado esta inactivo). En el diagrama la fila apellidoEmpleado aparece
-- dos veces; la segunda es probablemente este mail (ver README).
CREATE TABLE cuenta_empleado (
    empleado_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mail              VARCHAR(200) NOT NULL,
    nombre_empleado   VARCHAR(25)  NOT NULL,
    apellido_empleado VARCHAR(25)  NOT NULL,
    rol               VARCHAR(50)  NOT NULL,
    activo            BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_empleado_mail UNIQUE (mail),
    CONSTRAINT ck_empleado_rol  CHECK (rol IN ('MESA_ENTRADAS', 'ADMINISTRATIVO', 'RESPONSABLE_AREA', 'AUDITOR'))
);

-- contrasenasEmpleados del diagrama. Mismo desvio de longitud que
-- credencial_persona: el hash BCrypt no entra en VARCHAR(50).
CREATE TABLE credencial_empleado (
    empleado_id BIGINT       PRIMARY KEY,
    password    VARCHAR(100) NOT NULL,
    CONSTRAINT fk_credencial_empleado FOREIGN KEY (empleado_id) REFERENCES cuenta_empleado (empleado_id) ON DELETE CASCADE
);

-- ------------------------------------------------------------------ INDICES ---
-- Solo los que sostienen busquedas del contrato; el resto los cubre la PK/unique.

-- RF-07: busqueda de ciudadanos por nombre/apellido y por estado.
CREATE INDEX ix_ciudadano_apellido ON ciudadano (lower(apellido));
CREATE INDEX ix_ciudadano_nombre   ON ciudadano (lower(nombre));
CREATE INDEX ix_ciudadano_estado   ON ciudadano (estado);

-- RF-07: busqueda inversa por email/telefono.
CREATE INDEX ix_contacto_valor ON contacto_ciudadano (lower(valor));

CREATE INDEX ix_pp_persona       ON personas_propiedades (id_persona);
CREATE INDEX ix_propiedad_barrio ON propiedades (id_barrio);

CREATE INDEX ix_representacion_persona      ON representacion (persona_id);
CREATE INDEX ix_representacion_organizacion ON representacion (organizacion_id);

CREATE INDEX ix_documento_persona ON documento (persona_id, tipo_documento);
CREATE INDEX ix_solicitud_titular ON solicitud_documentacion (titular_id, estado);

CREATE INDEX ix_expediente_persona ON expediente (persona_id);
CREATE INDEX ix_expediente_estado  ON expediente (estado);

CREATE INDEX ix_ipj_juridica ON integrantes_personas_juridicas (id_persona_juridica);

COMMIT;
